#ifndef AURA_CONFIG_H
#define AURA_CONFIG_H

#include <stdint.h>

#define AURA_GPIO_TRIG_LEFT 4U
#define AURA_GPIO_ECHO_LEFT 5U
#define AURA_GPIO_TRIG_CENTER 6U
#define AURA_GPIO_ECHO_CENTER 7U
#define AURA_GPIO_TRIG_RIGHT 8U
#define AURA_GPIO_ECHO_RIGHT 9U

#define AURA_GPIO_PWM_LEFT 18U
#define AURA_GPIO_PWM_CENTER 19U
#define AURA_GPIO_PWM_RIGHT 20U

#define AURA_DC_MOTOR_MIN_EFFECTIVE_DUTY 96U

#define AURA_POLL_CYCLE_MS 100U
#define AURA_NOTIFY_OFFSET_MS 95U
#define AURA_OVERRIDE_DURATION_MS 2000U

#define AURA_DISTANCE_MAX_CM 400U
#define AURA_DISTANCE_CLEAR_CM 200U
#define AURA_DISTANCE_APPROACHING_CM 150U
#define AURA_DISTANCE_NEAR_CM 100U
#define AURA_DISTANCE_VERY_NEAR_CM 50U
#define AURA_DISTANCE_DANGER_CM 20U

#define AURA_BATTERY_LOW_PERCENT 15U
#define AURA_BATTERY_CRITICAL_PERCENT 5U

#define AURA_STATUS_OK 0x00U
#define AURA_STATUS_LOW_BATTERY 0x01U
#define AURA_STATUS_CRITICAL_BATTERY 0x02U
#define AURA_STATUS_SENSOR_FAULT 0x03U

#endif