include $(APPDIR)/Make.defs

PROGNAME = aura_vest
PRIORITY = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE = $(CONFIG_EXAMPLES_AURA_VEST)

MAINSRC = aura_vest_main.c
CSRCS += aura_vest_http.c

include $(APPDIR)/Application.mk
